title: IAS Documentation
description: A starter template for a Jeykll site using the Just the Docs theme!

#remote_theme: just-the-docs/just-the-docs
theme: just-the-docs
#url: https://github.com/IAS-Uni-Siegen

aux_links:
  Template Repository: https://github.com/IAS-Uni-Siegen



plugins:
  - jekyll-default-layout
